### ISSUE TITLE
Newline breaks the layout of interactive style editors

### ISSUE THREAD

**Issue by JacobLinCool** [master-co/styles#1]
First of all, thanks to you guys for creating this amazing on-demand CSS engine.

When I am browsing the document, the interactive style editors work great, but newlines will break the layout even if it has been deleted. I think that will be nice if we ignore it.

By the way, I cannot find the repository of the document, will it be open to everyone soon?

**Comment by 1Aron** [comment]
Sorry, I'm busy replying to messages from the various communities, and I want to be the first to reply to you, so I'm late.
Thx for your support !
We are aware of this issue and have listed it as a pending fix.
Our Master project structure is very complex and is not a monorepo or multiple repo structure.
We are designing a special structure where resources are shared but project documents can be independent, if you have any questions about a specific project you can reply under its issue.

**Comment by BenSeage** [comment]
The style editor has been modified to prevent user from typing newlines.

If you have any other questions, please let us know and we will deal with it as soon as possible.

Thanks again for your support.
