### ISSUE TITLE
Remix browser check not ideal

### ISSUE THREAD

**Issue by HurricanKai** [master-co/styles#10]
Remix actually suggests to check for `document` instead of `window` due to deno supporting `window`
[see the official docs](https://remix.run/docs/en/v1/pages/gotchas#typeof-window-checks)
I've noticed the window check in the docs, not sure whether its also an issue in the code itself. (Coincidentally the latest commit also mentions a typeof window check 😛)

**Comment by 0Lola** [comment]
Thanks for your reminder.

1. `typeof window !== 'undefined'` already fixed at [1.3.0](https://github.com/master-co/styles/releases/tag/v1.3.).
2. It seems just need to import '@master/styles' in `entry.client.tsx`.

```tsx
import { hydrate } from "react-dom";
import { RemixBrowser } from "remix";

import '@master/styles';
hydrate( <RemixBrowser />, document);
```

It's works, we will update docs soon.

Better suggestions are welcome. 🥳
