### ISSUE TITLE
PNPM should also install `@master/style` manually.

### ISSUE THREAD

**Issue by JacobLinCool** [master-co/styles#13]
When I am using `pnpm` to install `@master/styles`, the warning shows up.

```
 WARN  Issues with peer dependencies found
.
├─┬ @master/styles
│ └── ✕ missing peer @master/style@^1.0.0
```

After digging into the source code, I found that in `package.json`, the package states `@master/style` as its peer dependency:

```json
"peerDependencies": {
    "@master/style": "^1.0.0"
},
```

~~I don't know if it is necessary to do so? Is `@master/style` bundled in `@master/styles`?~~

I think the document of `pnpm` setup instruction should be:

```sh
pnpm install @master/styles @master/style @master/normal.css
```

because `pnpm` won't automatically install peer dependencies by default.

> Node: `16.13.1`
> PNPM: `6.32.3`
> @master/styles: `1.3.1`

**Comment by 1Aron** [comment]
@JacobLinCool Issues with pnpm have been fixed and updated. 
We are working on refactoring the official website from Angular to Nextjs, sorry for the late reply.
Thanks for following our open source project. 🥰
