### ISSUE TITLE
Feature: Support for non-standard CSS properties (using generated vendor prefixes)

### ISSUE THREAD

**Issue by brycetsao** [master-co/styles#6]
Some of the non-standard properties are supported by generating vendor prefixes, e.g., `-webkit-font-smoothing, -moz-osx-font-smoothing`; while some others are not supported yet, e.g., `-webkit-text-stroke`.
In order to support features like `-webkit-text-stroke`, we may either enable keywords transpilation of vendor prefixes, or create corresponding classes for all available non-standard properties. The former may still be a fail-safe solution even if the latter approach is preferred.

**Comment by BenSeage** [comment]
**text-stroke** / **text-stroke-width** / **text-stroke-color** had been added to version 1.1.0.

You can typing **text-stroke:1;red**, **text-stroke:1**, **text-stroke:red**... in class to test.

Thanks for taking the time to report back.
